### ISSUE TITLE
Image.build_from_dir Couldn't find id:

### ISSUE THREAD

**Issue by kpettijohn** [swipely/docker-api#255]
Running into a issue with `Image.build_from_dir`. Any insight on whats causing `extract_id` to not find the docker image id would be greatly appreciated!

`Docker::Image.build_from_dir("ops/docker/#{image}", &output)`

```
Couldn't find id: {"stream":"Step 0 : FROM debian:jessie\n"}
{"stream":" ---\u003e 58052b122b60\n"}
{"stream":"Step 1 : RUN groupadd -r redis \u0026\u0026 useradd -r -g redis redis\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 53ab858e2dcc\n"}
{"stream":"Step 2 : RUN apt-get update   \u0026\u0026 apt-get install -y curl   \u0026\u0026 rm -rf /var/lib/apt/lists/*\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e fc3a60e35317\n"}
{"stream":"Step 3 : RUN gpg --keyserver pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e fac52effd68e\n"}
{"stream":"Step 4 : RUN curl -o /usr/local/bin/gosu -SL \"https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture)\"   \u0026\u0026 curl -o /usr/local/bin/gosu.asc -SL \"https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture).asc\"   \u0026\u0026 gpg --verify /usr/local/bin/gosu.asc   \u0026\u0026 rm /usr/local/bin/gosu.asc   \u0026\u0026 chmod +x /usr/local/bin/gosu\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 446bffb3a2e6\n"}
{"stream":"Step 5 : ENV REDIS_VERSION 2.6.17\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 32959224175f\n"}
{"stream":"Step 6 : ENV REDIS_DOWNLOAD_URL http://download.redis.io/releases/redis-2.6.17.tar.gz\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 5b3b5aa2fb01\n"}
{"stream":"Step 7 : ENV REDIS_DOWNLOAD_SHA1 b5423e1c423d502074cbd0b21bd4e820409d2003\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 1b0ae9ebbe3f\n"}
{"stream":"Step 8 : RUN buildDeps='gcc libc6-dev make';   set -x   \u0026\u0026 apt-get update \u0026\u0026 apt-get install -y $buildDeps --no-install-recommends   \u0026\u0026 rm -rf /var/lib/apt/lists/*   \u0026\u0026 mkdir -p /usr/src/redis   \u0026\u0026 curl -sSL \"$REDIS_DOWNLOAD_URL\" -o redis.tar.gz   \u0026\u0026 echo \"$REDIS_DOWNLOAD_SHA1 *redis.tar.gz\" | sha1sum -c -   \u0026\u0026 tar -xzf redis.tar.gz -C /usr/src/redis --strip-components=1   \u0026\u0026 rm redis.tar.gz   \u0026\u0026 make -C /usr/src/redis   \u0026\u0026 make -C /usr/src/redis install   \u0026\u0026 ln -s redis-server \"$(dirname \"$(which redis-server)\")/redis-sentinel\"   \u0026\u0026 rm -r /usr/src/redis   \u0026\u0026 apt-get purge -y --auto-remove $buildDeps\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e a3993a272a39\n"}
{"stream":"Step 9 : RUN mkdir /redis-data \u0026\u0026 chown redis:redis /redis-data\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 53b9b5c98135\n"}
{"stream":"St
27
{"stream":
/vendor/bundle/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/util.rb:142:in `extract_id'
/vendor/bundle/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:234:in `build_from_tar'
/vendor/bundle/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:246:in `build_from_dir'
/Rakefile:214:in `block (4 levels) in <top (required)>'
/Rakefile:209:in `each'
/Rakefile:209:in `block (3 levels) in <top (required)>'
Tasks: TOP => ops:dev:build
(See full trace by running task with --trace)
```
EXCON_DEBUG=true
```
excon.request
  :chunk_size          => 1048576
  :ciphers             => "HIGH:!SSLv2:!aNULL:!eNULL:!3DES"
  :client_cert         => "/Users/kpettijohn/.boot2docker/certs/boot2docker-vm/cert.pem"
  :client_key          => "/Users/kpettijohn/.boot2docker/certs/boot2docker-vm/key.pem"
  :connect_timeout     => 60
  :debug_request       => true
  :debug_response      => true
  :expects             => [
    200
    201
    202
    203
    204
    304
  ]
  :headers             => {
    "Content-Type" => "text/plain"
    "Host"         => "192.168.59.103:2376"
    "User-Agent"   => "Swipely/Docker-API 1.19.0"
  }
  :host                => "192.168.59.103"
  :hostname            => "192.168.59.103"
  :idempotent          => true
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => :get
  :middlewares         => [
    Excon::Middleware::Hijack
    Excon::Middleware::ResponseParser
    Excon::Middleware::Expects
    Excon::Middleware::Idempotent
    Excon::Middleware::Instrumentor
    Excon::Middleware::Mock
  ]
  :mock                => false
  :nonblock            => true
  :omit_default_port   => false
  :path                => "/v1.16/version"
  :persistent          => false
  :port                => 2376
  :query               => {
  }
  :read_timeout        => 60
  :retries_remaining   => 4
  :retry_limit         => 4
  :scheme              => "https"
  :ssl_ca_file         => "/Users/kpettijohn/.boot2docker/certs/boot2docker-vm/ca.pem"
  :ssl_verify_peer     => true
  :tcp_nodelay         => false
  :thread_safe_sockets => true
  :uri_parser          => URI
  :versions            => "excon/0.44.2 (universal.x86_64-darwin13) ruby/2.0.0"
  :write_timeout       => 60
excon.response
  :body          => "{\"ApiVersion\":\"1.17\",\"Arch\":\"amd64\",\"GitCommit\":\"a8a31ef\",\"GoVersion\":\"go1.4.1\",\"KernelVersion\":\"3.18.5-tinycore64\",\"Os\":\"linux\",\"Version\":\"1.5.0\"}\n"
  :headers       => {
    "Content-Length" => "148"
    "Content-Type"   => "application/json"
    "Date"           => "Tue, 24 Feb 2015 19:30:32 GMT"
    "Job-Name"       => "version"
  }
  :local_address => "192.168.59.3"
  :local_port    => 51041
  :reason_phrase => "OK"
  :remote_ip     => "192.168.59.103"
  :status        => 200
{"ApiVersion"=>"1.17", "Arch"=>"amd64", "GitCommit"=>"a8a31ef", "GoVersion"=>"go1.4.1", "KernelVersion"=>"3.18.5-tinycore64", "Os"=>"linux", "Version"=>"1.5.0"}
excon.request
  :chunk_size          => 1048576
  :ciphers             => "HIGH:!SSLv2:!aNULL:!eNULL:!3DES"
  :client_cert         => "/Users/kpettijohn/.boot2docker/certs/boot2docker-vm/cert.pem"
  :client_key          => "/Users/kpettijohn/.boot2docker/certs/boot2docker-vm/key.pem"
  :connect_timeout     => 60
  :debug_request       => true
  :debug_response      => true
  :expects             => [
    200
    201
    202
    203
    204
    304
  ]
  :headers             => {
    "Content-Type"      => "application/tar"
    "Host"              => "192.168.59.103:2376"
    "Transfer-Encoding" => "chunked"
    "User-Agent"        => "Swipely/Docker-API 1.19.0"
    "X-Registry-Config" => "eyJjqwerqweaWdzIjpsdfgHBzOisddfg8vZG9ja2VyLdfasdfnBkeC5lc3JpLDFSI6eyJ1c2VybmFtZSI6ImVzcmktZG9ja2VyasdfGFzc3dvasdfcmQiOiasfc3RyWSWlsIjoin19fQ=="
  }
  :host                => "192.168.59.103"
  :hostname            => "192.168.59.103"
  :idempotent          => false
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => :post
  :middlewares         => [
    Excon::Middleware::Hijack
    Excon::Middleware::ResponseParser
    Excon::Middleware::Expects
    Excon::Middleware::Idempotent
    Excon::Middleware::Instrumentor
    Excon::Middleware::Mock
  ]
  :mock                => false
  :nonblock            => true
  :omit_default_port   => false
  :path                => "/v1.16/build"
  :persistent          => false
  :port                => 2376
  :query               => {
  }
  :read_timeout        => 60
  :request_block       => #<Proc:0x007fc180b155a0@/vendor/bundle/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:231>
  :response_block      => #<Proc:0x007fc180b15640@/vendor/bundle/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:296 (lambda)>
  :retries_remaining   => 4
  :retry_limit         => 4
  :scheme              => "https"
  :ssl_ca_file         => "/Users/kpettijohn/.boot2docker/certs/boot2docker-vm/ca.pem"
  :ssl_verify_peer     => true
  :tcp_nodelay         => false
  :thread_safe_sockets => true
  :uri_parser          => URI
  :versions            => "excon/0.44.2 (universal.x86_64-darwin13) ruby/2.0.0"
  :write_timeout       => 60
```

Docker info
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by kpettijohn** [comment]
I spent a bit more time looking into this issue further and unless I'm missing something this might actually be an issue with the `excon` gem.

Each time I ran the build it would fail on `extract_id ` at different points when building the `body` response. It seemed like the response was being truncated before the whole response made it back from Excon (https://github.com/excon/excon/blob/master/lib/excon/response.rb#L92-L104). When stepping through the response using `byebug` the build would return the full response correctly. 

As a test I placed `sleep(1.0/3.0)` at line 95 (https://github.com/excon/excon/blob/master/lib/excon/response.rb#L95) and the build would finish successfully without error. It seems like the overall problem has to do with the timing/reading on the socket from exon. 

Here is a similar issue from Excon - https://github.com/excon/excon/issues/399

If we think that this is an issue with Excon let me know and I can open an issue.

**Comment by tlunter** [comment]
@kpettijohn This does seem to be `excon` related.  I haven't noticed this issue though, and I've been using `excon` v0.44.2 as well.  The response is definitely missing the last line where we extract the image id.  My response looks like:

```
illyrio∴ be ruby test.rb
{"stream":"Step 0 : FROM ubuntu:14.04\n"}
{"stream":" ---\u003e 2d24f826cb16\n"}
{"stream":"Step 1 : RUN true\n"}
{"stream":" ---\u003e Running in 3f7e6fbae289\n"}
{"stream":" ---\u003e 77b06a636656\n"}
{"stream":"Removing intermediate container 3f7e6fbae289\n"}
{"stream":"Successfully built 77b06a636656\n"}
illyrio∴ be ruby test.rb
{"stream":"Step 0 : FROM ubuntu:14.04\n"}
{"stream":" ---\u003e 2d24f826cb16\n"}
{"stream":"Step 1 : RUN true\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 77b06a636656\n"}
{"stream":"Successfully built 77b06a636656\n"}
illyrio∴ be ruby test.rb
{"stream":"Step 0 : FROM ubuntu:14.04\n"}
{"stream":" ---\u003e 2d24f826cb16\n"}
{"stream":"Step 1 : RUN true\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 77b06a636656\n"}
{"stream":"Successfully built 77b06a636656\n"}
```

**Comment by kpettijohn** [comment]
@tlunter I ended up trying the same setup on debian/jessie with `excon` v0.42.2 and was unable to recreate the issue so it must be something with my OS X 10.9.5/boot2docker setup. 

It seems to happen at random points in the response and even returns a HTTP status of `0 Unknown` at times. If I have the time to investigate further I will update the issue with my findings. 

Thanks for taking the time to have a look! 

```
$ bundle exec rake build
rake aborted!
Docker::Error::UnexpectedResponseError: Couldn't find id: {"stream":"Step 0 : FROM debian:jessie\n"}
{"stream":" ---\u003e 0e30e84e9513\n"}
{"stream":"Step 1 : RUN groupadd -r redis \u0026\u0026 useradd -r -g redis redis\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 3f8d3331e4bc\n"}
{"stream":"Step 2 : RUN apt-get update   \u0026\u0026 apt-get install -y curl   \u0026\u0026 rm -rf /var/lib/apt/lists/*\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 15d0ffaaf707\n"}
{"stream":"Step 3 : RUN gpg --keyserver pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 70ffbbb8b28a\n"}
{"stream":"Step 4 : RUN curl -o /usr/local/bin/gosu -SL \"https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture)\"   \u0026\u0026 curl -o /usr/local/bin/gosu.asc -SL \"https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture).asc\"   \u0026\u0026 gpg --verify /usr/local/bin/gosu.asc   \u0026\u0026 rm /usr/local/bin/gosu.asc   \u0026\u0026 chmod +x /usr/local/bin/gosu\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e a0d3f1222e74\n"}
{"stream":"Step 5 : ENV REDIS_VERSION 2.6.17\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e c992e9a177fd\n"}
{"stream":"Step 6 : ENV REDIS_DOWNLOAD_URL http://download.redis.io/releases/redis-2.6.17.tar.gz\n"}
{"strea
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/util.rb:142:in `extract_id'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:236:in `build_from_tar'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:248:in `build_from_dir'
/Users/kpettijohn/Work/GT/docker/Rakefile:14:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)


$ bundle exec rake build
rake aborted!
Excon::Errors::HTTPStatusError: Expected([200, 201, 202, 203, 204, 304]) <=> Actual(0 Unknown)
/Users/kpettijohn/.gems/ruby/2.0.0/gems/excon-0.44.1/lib/excon/middlewares/expects.rb:6:in `response_call'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/excon-0.44.1/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/excon/middlewares/hijack.rb:45:in `response_call'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/excon-0.44.1/lib/excon/connection.rb:372:in `response'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/excon-0.44.1/lib/excon/connection.rb:236:in `request'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/connection.rb:44:in `request'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/connection.rb:61:in `block (2 levels) in <class:Connection>'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:227:in `build_from_tar'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:248:in `build_from_dir'
/Users/kpettijohn/Work/docker/Rakefile:14:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)


$ bundle exec rake build
rake aborted!
Docker::Error::UnexpectedResponseError: Couldn't find id: {"stream":"Step 0 : FROM debian:jessie\n"}
{"stream":" ---\u003e 0e30e84e9513\n"}
{"stream":"Step 1 : RUN groupadd -r redis \u0026\u0026 useradd -r -g redis redis\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 3f8d3331e4bc\n"}
{"stream":"Step 2 : RUN apt-get update   \u0026\u0026 apt-get install -y curl   \u0026\u0026 rm -rf /var/lib/apt/lists/*\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/util.rb:142:in `extract_id'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:236:in `build_from_tar'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:248:in `build_from_dir'
/Users/kpettijohn/Work/docker/Rakefile:14:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)


$ bundle exec rake build
rake aborted!
Docker::Error::UnexpectedResponseError: Couldn't find id: {"stream":"Step 0 : FROM debian:jessie\n"}
{"stream":" ---\u003e 0e30e84e9513\n"}
{"stream":"Step 1 : RUN groupadd -r redis \u0026\u0026 useradd -r -g redis redis\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 3f8d3331e4bc\n"}
{"stream":"Step 2 : RUN apt-get update   \u0026\u0026 apt-get install -y curl   \u0026\u0026 rm -rf /var/lib/apt/lists/*\n"}
{"strea
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/util.rb:142:in `extract_id'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:236:in `build_from_tar'
/Users/kpettijohn/.gems/ruby/2.0.0/gems/docker-api-1.19.0/lib/docker/image.rb:248:in `build_from_dir'
/Users/kpettijohn/Work/docker/Rakefile:14:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)
```
