### ISSUE TITLE
Boot2docker and TLS

### ISSUE THREAD

**Issue by ftomassetti** [swipely/docker-api#270]
Hi, I would like to be able to operate with boo2docker without disabling TLS (i.e., working with boot2docker out of the box).

What should I do?
I tried running:

```
Excon.defaults[:ssl_verify_peer] = false
```

And now I can create a container and start it (apparently) but it does not start for real:

```
2.2.0 :294 > container = Docker::Container.create('Image' => 'db_container')
 => #<Docker::Container:0x007faffb0a4260 @id="89a3c2236dd516f3b50eac7092265c24f0dbf58fad8632a0d979c4417fda18f0", @info={"Warnings"=>nil, "id"=>"89a3c2236dd516f3b50eac7092265c24f0dbf58fad8632a0d979c4417fda18f0"}, @connection=#<Docker::Connection:0x007faffb1143a8 @url="tcp://192.168.59.103:2376", @options={:client_cert=>"/Users/ftomassetti/.boot2docker/certs/boot2docker-vm/cert.pem", :client_key=>"/Users/ftomassetti/.boot2docker/certs/boot2docker-vm/key.pem", :ssl_ca_file=>"/Users/ftomassetti/.boot2docker/certs/boot2docker-vm/ca.pem", :scheme=>"https"}>>
2.2.0 :295 > container.start
 => #<Docker::Container:0x007faffb0a4260 @id="89a3c2236dd516f3b50eac7092265c24f0dbf58fad8632a0d979c4417fda18f0", @info={"Warnings"=>nil, "id"=>"89a3c2236dd516f3b50eac7092265c24f0dbf58fad8632a0d979c4417fda18f0"}, @connection=#<Docker::Connection:0x007faffb1143a8 @url="tcp://192.168.59.103:2376", @options={:client_cert=>"/Users/ftomassetti/.boot2docker/certs/boot2docker-vm/cert.pem", :client_key=>"/Users/ftomassetti/.boot2docker/certs/boot2docker-vm/key.pem", :ssl_ca_file=>"/Users/ftomassetti/.boot2docker/certs/boot2docker-vm/ca.pem", :scheme=>"https"}>>
2.2.0 :296 > container.top
Docker::Error::ServerError: Container 89a3c2236dd516f3b50eac7092265c24f0dbf58fad8632a0d979c4417fda18f0 is not running

    from /Users/ftomassetti/.rvm/gems/ruby-2.2.0/gems/docker-api-1.20.0/lib/docker/connection.rb:54:in `rescue in request'
    from /Users/ftomassetti/.rvm/gems/ruby-2.2.0/gems/docker-api-1.20.0/lib/docker/connection.rb:38:in `request'
    from /Users/ftomassetti/.rvm/gems/ruby-2.2.0/gems/docker-api-1.20.0/lib/docker/connection.rb:61:in `block (2 levels) in <class:Connection>'
    from /Users/ftomassetti/.rvm/gems/ruby-2.2.0/gems/docker-api-1.20.0/lib/docker/container.rb:8:in `top'
    from (irb):296
    from /Users/ftomassetti/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

**Comment by estahn** [comment]
:+1:

**Comment by tlunter** [comment]
@estahn is DOCKER_CERT_PATH set in your environment, but not valid for the current DOCKER_HOST? Trying to understand why you wouldn't want to set the certificates if that env variable is set.

**Comment by estahn** [comment]
@tlunter I was under the impression you can run docker without TLS. I might be wrong.

**Comment by tlunter** [comment]
@estahn definitely! But I figured DOCKER_CERT_PATH wouldn't be set if you weren't using TLS. `docker-api` will automatically enable passing the certificates if DOCKER_CERT_PATH is set.  If you aren't using TLS, removing that from your environment should fix this problem.
