### ISSUE TITLE
Creating image: `rescue in request': read timeout reached (Docker::Error::TimeoutError)

### ISSUE THREAD

**Issue by mustela** [swipely/docker-api#301]
I'm just trying to create an image and all I got is the timeout error. 

This is the code I'm using: 

```
Docker.options[:read_timeout] = 1000
Docker.options[:write_timeout] = 1000
Docker::Image.create('fromImage' => 'ubuntu')
```

This is the error

```
/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/docker-api-1.22.1/lib/docker/connection.rb:52:in `rescue in request': read timeout reached (Docker::Error::TimeoutError)
	from /Users/mustela/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/docker-api-1.22.1/lib/docker/connection.rb:38:in `request'
	from /Users/mustela/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/docker-api-1.22.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	from /Users/mustela/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/docker-api-1.22.1/lib/docker/event.rb:20:in `stream'
	from /Users/mustela/Sites/packet/hall/lib/hall/docky.rb:26:in `update_app'
	from /Users/mustela/Sites/packet/hall/lib/hall.rb:70:in `docker'
	from /Users/mustela/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/mustela/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mustela/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/mustela/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/mustela/Sites/packet/hall/lib/hall.rb:90:in `<top (required)>'
	from exe/hall:3:in `require'
	from exe/hall:3:in `<main>'

```

I'm using the last gem: `1.22.2`

Also, doing `Docker.info` just works as expected. Same with `Docker.authenticate!`, so not sure whats going on here. 

Any clue would be awesome! 

Thanks

**Comment by tlunter** [comment]
Hi @mustela, that command does have a chance to timeout if docker is pulling the ubuntu image and takes longer than the read timeout.  I feel like 1000 seconds would've been enough though.  Usually this means that docker is still pulling the image from the docker hub.  If you do a `docker pull ubuntu` from the CLI, you should end up with a similar result or something that says `this image is already being pulled`.  If you don't, then we'll need to delve into what docker is giving you back.

You can also get a streaming output by passing a block:

```
Docker.options[:read_timeout] = 1000
Docker.options[:write_timeout] = 1000

Docker::Image.create('fromImage' => 'ubuntu') do |chunk|
  puts chunk
end
```

**Comment by mustela** [comment]
Hey @tlunter I just add the block and now I can see 

```
{"status":"Downloading","progressDetail":{"current":1365470,"total":-1},"progress":"1.365 MB","id":"f0dde87450ec"}
{"status":"Error downloading dependent layers","progressDetail":{},"id":"f0dde87450ec"}
{"status":"Error pulling image (trusty-20150228.11) from ubuntu, endpoint: https://registry-1.docker.io/v1/, Untar exit status 1 unexpected EOF","progressDetail":{},"id":"2103b00b3fdf"}
{"status":"Error pulling image (trusty-20150228.11) from ubuntu, Untar exit status 1 unexpected EOF","progressDetail":{},"id":"2103b00b3fdf"}
{"status":"Downloading","progressDetail":{"current":1078176,"total":-1},"progress":"1.078 MB","id":"77ea55b60d7f"}
{"status":"Downloading","progressDetail":{"current":1610240,"total":-1},"progress":" 1.61 MB","id":"4f5adcadb2a9"}
{"status":"Downloading","progressDetail":{"current":1607344,"total":-1},"progress":"1.607 MB","id":"a43c2c5b6472"}
{"status":"Downloading","progressDetail":{"current":711024,"total":-1},"progress":"  711 kB","id":"3af9d794ad07"}
{"status":"Error downloading dependent layers","progressDetail":{},"id":"3af9d794ad07"}
{"status":"Error pulling image (raring) from ubuntu, endpoint: https://registry-1.docker.io/v1/, Untar exit status 1 unexpected EOF","progressDetail":{},"id":"463ff6be4238"}
{"status":"Error pulling image (raring) from ubuntu, Untar exit status 1 unexpected EOF","progressDetail":{},"id":"463ff6be4238"}
````
Is that a normal output? Or maybe their api isn't working properly ?

**Comment by mustela** [comment]
Also running `docker pull ubuntu` while the lib is still running, just gave me this : 

```
docker pull ubuntu
latest: Pulling from ubuntu
83e4dde6b9cf: Already exists
b670fb0c7ecd: Already exists
29460ac93442: Already exists
d2a0ecffe6fa: Already exists
Digest: sha256:cb90b1a107073ab3e17271e45a6177b23f548b44157d88d955b7e8bcdbcfd14a
Status: Image is up to date for ubuntu:latest

```

**Comment by tlunter** [comment]
@mustela that is very interesting.  Looks like docker is dying trying to grab the image. Any reports on their registry acting up?  A lot of times the CLI is hiding something too.  They could be talking to a different registry.

**Comment by mustela** [comment]
@tlunter well everything seems to be `operational` there... so its a matter of checking it again in a few, since there isn't much to do here right, from a ruby perspective? 

Thanks

**Comment by tlunter** [comment]
@mustela definitely.

**Comment by mustela** [comment]
Ok, will just close it then. Thanks for the support!
