### ISSUE TITLE
Image create has mysterious error when image is not found

### ISSUE THREAD

**Issue by bradleyd** [swipely/docker-api#315]
When you try 

``` ruby
Docker::Image.create("fromImage" => "hopefully/shouldnotexistever", "tag" => "latest")
```

The response is about missing `id`

```
Docker::Error::ArgumentError: Must have id, got: {"id"=>nil, :headers=>{}}
    /Users/bradleyd/.rvm/gems/ruby-2.2.1@et-plugin-deploy-docker/gems/docker-api-1.22.4/lib/docker/base.rb:16:in `initialize'
    /Users/bradleyd/.rvm/gems/ruby-2.2.1@et-plugin-deploy-docker/gems/docker-api-1.22.4/lib/docker/image.rb:117:in `new'
    /Users/bradleyd/.rvm/gems/ruby-2.2.1@et-plugin-deploy-docker/gems/docker-api-1.22.4/lib/docker/image.rb:117:in `create'
    /Users/bradleyd/Projects/et/et-plugin-docker-deploy/lib/et/plugin/docker/deploy/connection.rb:27:in `pull'
    test/et/plugin/deploy/docker_commands_test.rb:10:in `test_finds_current_running_container'
```

The actual return is 

``` ruby
[{"status"=>"Pulling repository shouldnotexits"}, {"errorDetail"=>{"message"=>"Error: image library/shouldnotexits:latest not found"}, "error"=>"Error: image library/shouldnotexits:latest not found"}]}
```

Is this behavior expected?  If not a quick check on `errorDetail` from body and raise error with `errorDetail` should suffice.  

Would you accept a PR for this?

Take care,
Brad

**Comment by tlunter** [comment]
@bradleyd yes, feel free to open a PR for that.
