### ISSUE TITLE
Support for more recent Docker versions?

### ISSUE THREAD

**Issue by Govinda-Fichtner** [swipely/docker-api#323]
Is the statement in the README still true that only Docker-Engine version 1.3 is supported?

I tried to run docker-api with version Docker-Eninge version 1.8.3 and it worked for some commands, but for container.exec commands I always got

```
/usr/local/bundle/gems/docker-api-1.22.4/lib/docker/connection.rb:50:in `rescue in request': json: cannot unmarshal string into Go value of type []string (Docker::Error::ServerError)
    from /usr/local/bundle/gems/docker-api-1.22.4/lib/docker/connection.rb:38:in `request'
    from /usr/local/bundle/gems/docker-api-1.22.4/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
    from /usr/local/bundle/gems/docker-api-1.22.4/lib/docker/exec.rb:22:in `create'
    from /usr/local/bundle/gems/docker-api-1.22.4/lib/docker/container.rb:52:in `exec'
    from poller.rb:25:in `block in <main>'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:413:in `block in yield_messages'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412:in `each'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412:in `yield_messages'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405:in `block in process_messages'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `catch'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `process_messages'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336:in `block (2 levels) in poll'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `loop'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `block in poll'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `catch'
    from /usr/local/bundle/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll'
    from poller.rb:23:in `<main>'
```

**Comment by tlunter** [comment]
`docker-api` actually supports versions later than 1.3, since a lot of the endpoints have stayed the same.  I think we might even support some newer functionality since it's not really version namespaced correctly in the daemon.

I'm not sure which parameter exactly docker changed, but it might be that your command your passing in needs to be in an array versus just a string.

**Comment by xmik** [comment]
@Govinda-Fichtner, try solution from [#266](https://github.com/swipely/docker-api/issues/266#issuecomment-152518705)

**Comment by jakolehm** [comment]
I think version should be bumped asap to 1.18 (at least) because Docker Hub does not allow docker < 1.6 clients to pull/push images after December 7, 2015.

https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/
