### ISSUE TITLE
Deleteing containers/images after test

### ISSUE THREAD

**Issue by arukaen** [swipely/docker-api#330]
Trying to get rspec to delete the container after the test finishes but I seem to be having an error.

```ruby

require 'serverspec'
require 'docker'

describe 'Dockerfile' do
    before(:all) do
        image = Docker::Image.build_from_dir('.')

        set :os, family: :debian
        set :backend, :docker
        set :docker_image, image.id
    end
    after(:all) do
        @image.remove(:force => true)
    end

    it 'pulls the right version of Ubuntu' do
        expect(os_version).to include('Ubuntu 14')
    end

    it 'installs git' do
        expect(package('git')).to be_installed
    end

    def os_version
        command('lsb_release -a').stdout
    end
end
```

```sh
An error occurred in an `after(:context)` hook.
  NoMethodError: undefined method `remove' for nil:NilClass
  occurred at /Users/me/docker/mumble-server/spec/Dockerfile_spec.rb:13:in `block (2 levels) in <top (required)>'



Finished in 0.96545 seconds (files took 0.96537 seconds to load)
2 examples, 0 failures
```

**Comment by tlunter** [comment]
You have:

```
image = Docker::Image.build_from_dir('.')
```

and are trying to use `@image`.  Try replacing the top `image` with `@image`.

**Comment by arukaen** [comment]
@tlunter If I make the top @image = Docker... it breaks even worse. I edited the spec file and removed the @image and have just image.remove and it still fails as well.

```
..
An error occurred in an `after(:context)` hook.
  NameError: undefined local variable or method `image' for #<RSpec::ExampleGroups::Dockerfile after(:context) hook>
  occurred at /Users/me/.chefdk/gem/ruby/2.1.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers.rb:966:in `method_missing'
```

**Comment by tlunter** [comment]
@arukaen I was suggesting making both `@image`.  Generally in rspec, you would do: 

```
    let(:image) { Docker::Image.build_from_dir('.') }

    before(:all) do
        set :os, family: :debian
        set :backend, :docker
        set :docker_image, image.id
    end
    after(:all) do
        image.remove(:force => true)
    end
```

Try this.

**Comment by arukaen** [comment]
Following your suggestion and still getting some errors.

```sh
rspec spec/Dockerfile_spec.rb
FF
An error occurred in an `after(:context)` hook.
  RuntimeError: let declaration `image` accessed in an `after(:context)` hook at:
  /Users/me/docker/git/spec/Dockerfile_spec.rb:14:in `block (2 levels) in <top (required)>'

`let` and `subject` declarations are not intended to be called
in an `after(:context)` hook, as they exist to define state that
is reset between each example, while `after(:context)` exists to
cleanup state that is shared across examples in an example group.

  occurred at /Users/me/.chefdk/gem/ruby/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/memoized_helpers.rb:207:in `fetch_or_store'



Failures:

  1) Dockerfile pulls the right version of Ubuntu
     Failure/Error: set :docker_image, image.id
     RuntimeError:
       let declaration `image` accessed in a `before(:context)` hook at:
         /Users/me/docker/git/spec/Dockerfile_spec.rb:11:in `block (2 levels) in <top (required)>'

       `let` and `subject` declarations are not intended to be called
       in a `before(:context)` hook, as they exist to define state that
       is reset between each example, while `before(:context)` exists to
       define state that is shared across examples in an example group.

     # ./spec/Dockerfile_spec.rb:11:in `block (2 levels) in <top (required)>'

  2) Dockerfile installs git
     Failure/Error: set :docker_image, image.id
     RuntimeError:
       let declaration `image` accessed in a `before(:context)` hook at:
         /Users/me/docker/git/spec/Dockerfile_spec.rb:11:in `block (2 levels) in <top (required)>'

       `let` and `subject` declarations are not intended to be called
       in a `before(:context)` hook, as they exist to define state that
       is reset between each example, while `before(:context)` exists to
       define state that is shared across examples in an example group.

     # ./spec/Dockerfile_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 0.00058 seconds (files took 0.93346 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/Dockerfile_spec.rb:17 # Dockerfile pulls the right version of Ubuntu
rspec ./spec/Dockerfile_spec.rb:21 # Dockerfile installs git
```

**Comment by tlunter** [comment]
```
    let(:image) { Docker::Image.build_from_dir('.') }

    before(:example) do
        set :os, family: :debian
        set :backend, :docker
        set :docker_image, image.id
    end
    after(:example) do
        image.remove(:force => true)
    end
```

This will perform the cleanup between each and every `it` block, but that is better testing anyway.  If you'd like to build the image only once, I'd suggest collapsing to a single `it` with many `expects`.

**Comment by arukaen** [comment]
Seems like I'm getting a bit closer but still running into errors.

```sh
No backend type is specified. Fall back to :exec type.
FF

Failures:

  1) Dockerfile pulls the right version of Ubuntu
     Failure/Error: image.remove(:force => true)
     Docker::Error::ConflictError:
       Conflict, cannot force delete d5d641ab5258 because the running container 287b52128276 is using it, stop it and retry

     # /Users/me/.chefdk/gem/ruby/2.1.0/gems/docker-api-1.22.4/lib/docker/connection.rb:48:in `rescue in request'
     # /Users/me/.chefdk/gem/ruby/2.1.0/gems/docker-api-1.22.4/lib/docker/connection.rb:38:in `request'
     # /Users/me/.chefdk/gem/ruby/2.1.0/gems/docker-api-1.22.4/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
     # /Users/me/.chefdk/gem/ruby/2.1.0/gems/docker-api-1.22.4/lib/docker/image.rb:69:in `remove'
     # ./spec/Dockerfile_spec.rb:14:in `block (2 levels) in <top (required)>'

  2) Dockerfile installs git
     Failure/Error: image.remove(:force => true)
     Docker::Error::ConflictError:
       Conflict, cannot force delete d5d641ab5258 because the running container 287b52128276 is using it, stop it and retry

     # /Users/me/.chefdk/gem/ruby/2.1.0/gems/docker-api-1.22.4/lib/docker/connection.rb:48:in `rescue in request'
     # /Users/me/.chefdk/gem/ruby/2.1.0/gems/docker-api-1.22.4/lib/docker/connection.rb:38:in `request'
     # /Users/me/.chefdk/gem/ruby/2.1.0/gems/docker-api-1.22.4/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
     # /Users/me/.chefdk/gem/ruby/2.1.0/gems/docker-api-1.22.4/lib/docker/image.rb:69:in `remove'
     # ./spec/Dockerfile_spec.rb:14:in `block (2 levels) in <top (required)>'

Finished in 49.26 seconds (files took 0.92359 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/Dockerfile_spec.rb:17 # Dockerfile pulls the right version of Ubuntu
rspec ./spec/Dockerfile_spec.rb:21 # Dockerfile installs git
```

This is what the Dockerfile_spec.rb looks like now:

```ruby
require 'serverspec'
require 'docker'

describe 'Dockerfile' do
    let(:image) { Docker::Image.build_from_dir('.') }

    before(:example) do

        set :os, family: :debian
        set :backend, :docker
        set :docker_image, image.id
    end
    after(:example) do
        image.remove(:force => true)
    end

    it 'pulls the right version of Ubuntu' do
        expect(os_version).to include('Ubuntu 14')
    end

    it 'installs git' do
        expect(package('git')).to be_installed
    end

    def os_version
        command('lsb_release -a').stdout
    end
end
```

**Comment by tlunter** [comment]
The containers are still running.  The output from `command()` seems to be leaving a container running.

```
require 'serverspec'
require 'docker'

describe 'Dockerfile' do
    let(:image) { Docker::Image.build_from_dir('.') }
    let(:container) { command('lsb_release -a') }
    let(:os_version) { container.stdout }
    before(:example) do

        set :os, family: :debian
        set :backend, :docker
        set :docker_image, image.id
    end
    after(:example) do
        container.remove(:force => true)
        image.remove(:force => true)
    end

    it 'pulls the right version of Ubuntu' do
        expect(os_version).to include('Ubuntu 14')
    end

    it 'installs git' do
        expect(package('git')).to be_installed
    end
end
```

I'm not sure where `package()` lives, or what the `command()` method actually returns, but this seems closer to what you're looking for.  You need to make sure the containers are dead or killed before removing their image.

**Comment by arukaen** [comment]
`lsb_release -a` returns distribution information on ubuntu.
```
root@vagrant-ubuntu-trusty-64:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

**Comment by tlunter** [comment]
@arukaen I meant what the ruby methods do.  Looks like some of this code isn't coming from `docker-api` but elsewhere.

**Comment by arukaen** [comment]
I'll keep playing with it. Maybe its not worth it to destroy the container/images after the test is done

**Comment by DevOps575** [comment]
Guys,

I am also facing the same issue. I am also not able to delete the image after testing. This is the spec file I am using:

describe 'image spec' do
  before(:all) do
    @image = Docker::Image.build_from_dir('.')
    set :os, family: :alpine
    set :backend, :docker
    set :docker_image, @image.id
  end
  after(:all) do
    @image.remove(:force => true)
  end
end

I am not sure how to stop/remove the container launched by API and it is not exposed anywhere.

From the error it seems container is still running and therefore not allowing to delete the image.

Failure/Error: @image.remove(:force => true)
Docker::Error::ConflictError:
  conflict: unable to delete 94934baaa85c (cannot be forced) - image is being used by running container d26f6e76dfcc

Thanks
