### ISSUE TITLE
(docker 1.10) Docker::Image.create('fromImage' => image_name) raises an exception after successful downloading an image

### ISSUE THREAD

**Issue by seffenberg-naspers** [swipely/docker-api#369]
Since docker 1.10 pulling from docker hub a private image will succeed but still throw an exception with `No such image:  a3ed95caeb02`:

```
INFO: [dff666b43ddc] Pull complete
INFO: [dff666b43ddc] Pull complete
INFO: [a3ed95caeb02] Extracting: 32/32 [==================================================>]     32 B/32 B
INFO: [a3ed95caeb02] Extracting: 32/32 [==================================================>]     32 B/32 B
INFO: [a3ed95caeb02] Pull complete
INFO: [a3ed95caeb02] Pull complete
INFO: Digest: sha256:3fa7ce9d9c7b4df549fa05f826823b0842ebe75c5e4191d91c4c4c1cba37c31d
INFO: Status: Downloaded newer image for organisation/private-image:1.0.0
ERROR: unexpected error while pulling image 'organisation/private-image:1.0.0'
ERROR: please ensure that you have network
ERROR: error message: No such image: a3ed95caeb02

ERROR: stacktrace:
/var/lib/gems/2.2.0/gems/docker-api-1.26.0/lib/docker/connection.rb:46:in `rescue in request'
/var/lib/gems/2.2.0/gems/docker-api-1.26.0/lib/docker/connection.rb:38:in `request'
/var/lib/gems/2.2.0/gems/docker-api-1.26.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
/var/lib/gems/2.2.0/gems/docker-api-1.26.0/lib/docker/image.rb:126:in `get'
/var/lib/gems/2.2.0/gems/docker-api-1.26.0/lib/docker/image.rb:118:in `create'
```

but the image was downloaded successfully:
```
gracy:~ [master f1d58b7]$ sudo docker images | grep private-image                                                                                                                        
organisation/private-image               1.0.0               075762755719        9 weeks ago         410 MB
```

the normal `sudo docker pull organisation/private-image` works also well

**Comment by seffenberg-naspers** [comment]
yeah I see also that the issue is after downloading it does
`{:method=>:get, :path=>"/v1.16/images/dff666b43ddc/json", :query=>{}, :headers=>{"Content-Type"=>"text/plain", "User-Agent"=>"Swipely/Docker-API 1.26.0"}, :expects=>[200, 201, 202, 203, 204, 304], :idempotent=>true}` which fails

**Comment by seffenberg-naspers** [comment]
worked locally (the fix)

**Comment by someara** [comment]
This seems to have broken the specs on Travis.... investigating

**Comment by seffenberg-naspers** [comment]
Temporary "fix" until this is solved and released:

```ruby
    begin
      Docker::Image.create('fromImage' => image_name) do |info|
        yield info if block_given?
      end 
    rescue Docker::Error::NotFoundError => e
      # see: https://github.com/swipely/docker-api/issues/369
      # as long as this is not fixed we need to re-check on our own
      # on docker-engines >= 1.10
      if Gem::Version.new(Docker.version['Version']) >= Gem::Version.new('1.10.0')
        Docker::Image.get(image_name)
      else
        raise e
      end 
    end 
```

**Comment by treeder** [comment]
Can we get the fix merged?

**Comment by tlunter** [comment]
Merged @someara's fix.  Sorry about the delay.

**Comment by SydOps** [comment]
The fix which @seffenberg-naspers pasted works for native docker for mac as well. 👍
