### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by waghanza** [swipely/docker-api#403]
Hi,

I'm playing with **containers** and a `strange` behavior appear.
I can start **container**s from latest image of :
- debian
- ubuntu
- centos
  but not `fedora`

My code

``` ruby
image = Docker::Image.create("fromImage" => "#{target}:latest").tag("repo" => "pg")
container = Docker::Container.create("Image" => "pg", "Tty" => true)
container.start
```

is ok but I have

``` ruby
Docker::Error::ServerError: No command specified

        from /var/lib/gems/2.1.0/gems/docker-api-1.28.0/lib/docker/connection.rb:50:in `rescue in request'
        from /var/lib/gems/2.1.0/gems/docker-api-1.28.0/lib/docker/connection.rb:38:in `request'
        from /var/lib/gems/2.1.0/gems/docker-api-1.28.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
        from /var/lib/gems/2.1.0/gems/docker-api-1.28.0/lib/docker/container.rb:277:in `create'
        from (irb):8
        from /usr/bin/irb:11:in `<main>'
```

when my `target` is `fedora`.

Has anybody an idea ?

The **Dockerfile**

``` dockerfile
FROM fedora:latest
```

pull right `fedora` version
Regards,

**Comment by carlochess** [comment]
Oh man, have you tried at least 
```ruby
image = Docker::Image.create("fromImage" => "#{target}:latest").tag("repo" => "pg")
container = Docker::Container.create('Cmd' => ['ls'], "Image" => "pg", "Tty" => true)
container.start
```
Your create command doesn't have the 'Cmd' parameter.

**Comment by hekaldama** [comment]
@waghanza did you get this resolved? Can you close if you did? Thanks.
