### ISSUE TITLE
Excon::Errors is now Excon::Error

### ISSUE THREAD

**Issue by jacobat** [swipely/docker-api#414]
It appears Excon decided to move all the error classes from `Excon::Errors` to `Excon::Error` in
https://github.com/excon/excon/commit/e300458f2d9330cb265baeb8973120d08c665d9c

This leads to:

```
irb(main):001:0> Docker::Image.all
NameError: uninitialized constant Excon::Errors::InternalServerError
Did you mean?  Excon::Errors::InternalServerErrorError
        from /usr/local/lib/ruby/gems/2.3.0/gems/docker-api-1.29.0/lib/docker/connection.rb:49:in `rescue in request'
        from /usr/local/lib/ruby/gems/2.3.0/gems/docker-api-1.29.0/lib/docker/connection.rb:38:in `request'
        from /usr/local/lib/ruby/gems/2.3.0/gems/docker-api-1.29.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
        from /usr/local/lib/ruby/gems/2.3.0/gems/docker-api-1.29.0/lib/docker/image.rb:194:in `all'
        from (irb):1
        from /usr/local/bin/irb:11:in `<main>'
```

Though Excon does provide support for the legacy errors it appears they've missed something here. But I suppose it's better to just get docker-api updated.

**Comment by lebedev-yury** [comment]
https://github.com/swipely/docker-api/pull/413
