### ISSUE TITLE
ssh connection

### ISSUE THREAD

**Issue by bubodlack** [swipely/docker-api#447]
Can i connect to socket to remote server with ssh connection?

**Comment by TonyRogers** [comment]
I currently use docker-machine to interract with remote containers. This uses ssh.

I would like to use the same ssh connections with docker-api. Is this possible? I haven't got http/s exposed.

**Comment by patrick-motard** [comment]
It's supported by docker ([documentation link](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option)). Example:

With a host defined in my `~/.ssh/config` called `myhost`:
```
docker -H ssh://myhost ps
```
or 
```
export DOCKER_HOST=ssh://myhost
docker ps
```
Either of the examples above will connect to the remote docker daemon over ssh.

I can't get this working in ruby via docker-api:
```
$> echo $DOCKER_HOST             
ssh://lahey
$> irb
irb(main):001:0> require 'docker'
=> true
irb(main):002:0> Docker.url
=> "ssh://myhost"
irb(main):003:0> Docker.info
Traceback (most recent call last):
       16: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/middlewares/base.rb:17:in `error_call'
       15: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
       14: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/connection.rb:275:in `request'
       13: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/middlewares/base.rb:22:in `request_call'
       12: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/middlewares/base.rb:22:in `request_call'
       11: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/middlewares/base.rb:22:in `request_call'
       10: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/middlewares/idempotent.rb:19:in `request_call'
        9: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/middlewares/instrumentor.rb:34:in `request_call'
        8: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/middlewares/mock.rb:57:in `request_call'
        7: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/middlewares/redirect_follower.rb:15:in `request_call'
        6: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/connection.rb:116:in `request_call'
        5: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/connection.rb:465:in `socket'
        4: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/connection.rb:465:in `new'
        3: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/socket.rb:47:in `initialize'
        2: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/socket.rb:119:in `connect'
        1: from /Users/pmotard/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/excon-0.72.0/lib/excon/socket.rb:119:in `getaddrinfo'
Excon::Error::Socket (getaddrinfo: nodename nor servname provided, or not known (SocketError))
irb(main):004:0> 
```

**Comment by Serhiy-Nazarov** [comment]
hello there!
Is it possible now to connect to the remote server with ssh connection?
