### ISSUE TITLE
Gem::Package::TooLongFileName on build image

### ISSUE THREAD

**Issue by eredi93** [swipely/docker-api#479]
when i try to do a build the split_name is breaking the build
```
/Users/jacopo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/package/tar_writer.rb:334:in `split_name': File "db/migrate/20160211090543_index_message_events_on_message_variation_id_and_subclass_type_reaction_set_id_and_reaction_index.rb" has a too long name (should be 100 or less) (Gem::Package::TooLongFileName)
	from /Users/jacopo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/docker-api-1.33.2/lib/docker/util.rb:169:in `add_file_to_tar'
	from /Users/jacopo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/docker-api-1.33.2/lib/docker/util.rb:155:in `block (2 levels) in create_relative_dir_tar'
	from /Users/jacopo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/docker-api-1.33.2/lib/docker/util.rb:150:in `each'
	from /Users/jacopo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/docker-api-1.33.2/lib/docker/util.rb:150:in `block in create_relative_dir_tar'
	from /Users/jacopo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/package/tar_writer.rb:86:in `new'
	from /Users/jacopo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/docker-api-1.33.2/lib/docker/util.rb:146:in `create_relative_dir_tar'
	from /Users/jacopo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/docker-api-1.33.2/lib/docker/util.rb:140:in `create_dir_tar'
	from /Users/jacopo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/docker-api-1.33.2/lib/docker/image.rb:277:in `build_from_dir'
```

**Comment by tlunter** [comment]
@eredi93 https://github.com/swipely/docker-api/issues/474
