### ISSUE TITLE
Dependency 'json' missing?

### ISSUE THREAD

**Issue by apophis90** [swipely/docker-api#519]
Hi,

When executing my serverspec tests within an Alpine-based Docker container with Ruby 2.4 installed, my tests always failed and I got the following stack trace:

```
1) Dockerfile has go package installed
     Failure/Error: @image = Docker::Image.build_from_dir('./variants/go')
     NameError:
       uninitialized constant Docker::Util::JSON
       
     # /home/jenkins/.gem/ruby/2.4.0/gems/docker-api-1.34.0/lib/docker/util.rb:244:in `build_config_header'
     # /home/jenkins/.gem/ruby/2.4.0/gems/docker-api-1.34.0/lib/docker/image.rb:308:in `build_headers'
     # /home/jenkins/.gem/ruby/2.4.0/gems/docker-api-1.34.0/lib/docker/image.rb:270:in `build_from_tar'
     # /home/jenkins/.gem/ruby/2.4.0/gems/docker-api-1.34.0/lib/docker/image.rb:293:in `build_from_dir'
     # ./spec/go/Dockerfile_spec.rb:12:in `block (2 levels) in <top (required)>
```

This first happened after I added the following line in my Dockerfile_spec.rb, which serves the purpose of doing a login to my private Docker registry:

```
Docker.authenticate!('username' => ENV['DOCKER_USERNAME'], 'password' => ENV['DOCKER_PASSWD'], 'serveraddress' => ENV['DOCKER_REGISTRY'])
```

I finally succeeded in fixing this by explicitly pulling the _json_ gem in my project's Gemfile:

```
source 'https://rubygems.org'

gem 'docker-api', :require => 'docker'
gem 'serverspec'
gem 'io-console'

gem 'json' # This line fixed my issue
```

Shouldn't this dependency be declared on your side?

Cheers,
Patrick

**Comment by tlunter** [comment]
Ah, darn, we converted to `MultiJson` but must've missed one use of `JSON`. Will fix.
